### ISSUE TITLE
Update block to `apiVersion: 2`

### ISSUE THREAD

**Issue by dinhtungdu** [10up/maps-block-apple#100]
By upgrading block to `apiVersion: 2`, we can use `useBlockProps` and `userBlockProps.save()` for edit and save component. We also can add global style using Block Supports API, but we may not need it for this block.

**Comment by fabiankaegy** [comment]
It will be very important for this to ensure that the markup we generate in the save function is thoroughly tested to ensure that we don't introduce any deprecation issues. And if we do see any we need to add them to the deprecations array :)
