### ISSUE TITLE
Block not responding to mouse events like dragging the map canvas when rendered in the iframed Site Editor

### ISSUE THREAD

**Issue by fabiankaegy** [10up/maps-block-apple#103]
This was discovered as a result of fixing #102 in #99. The Map itself does not respond to user interactions like dragging when it is rendered inside an iframe.

I think to verify this we should start by rendering a map inside an iframe outside of the editor to see whether it has something to do with mapkit or with WordPress.

**Comment by rahulsprajapati** [comment]
Hello @fabiankaegy 👋

I was looking into this and tried to test this in iframe, and I am able to drag the map in canvas.

ref:
![block-apple-map-#103](https://user-images.githubusercontent.com/10358350/142404876-ffa59876-e940-4d40-a499-52d30165f209.gif)

So, looks like this is WordPress specific issue when adding block in site editor.

---

I compare the render markup between edit post and site editor page, and I see there are some additional css class `mk-panning mk-dragging-cursor` in site editor markup:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/10358350/142405902-891cb7f1-0690-429a-a375-2796286ff8f3.png">


Not sure if this is helpful but so far I didn't see any obvious issue which leads to mapkit.
