### ISSUE TITLE
Old WordPress core support

### ISSUE THREAD

**Issue by cadic** [10up/maps-block-apple#127]
### Describe the bug

While working on #126 I've tested the plugin against every release since the current minimum support (5.2) to the latest 6.0 RC2. Found some issues in the old WordPress versions support.

#### Settings page

Saving settings fail in WordPress 5.5 and below. Adding correct credentials will return an error "Invalid Credentials!" (WP 5.5) or "The site is experiencing technical difficulties." (WP 5.2)

#### Block

The block isn't registered in WordPress 5.5 and below. There is no "Apple Maps" block in the list.

> Notice: WP_Block_Type_Registry::register was called incorrectly. Block type names must contain a namespace prefix. Example: my-plugin/my-custom-block-type Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 5.0.0.) in /var/www/html/wp-includes/functions.php on line 5225

### Steps to Reproduce

1. Install "Block for Apple Maps" on WordPress core prior to 5.5
2. Open Settings > Block for Apple Maps
3. Fill in correct credentials, save settings
4. The "MapKit status" will display unexpected error
5. Create new post/page
6. Search for Apple Maps block (not in the list)

### Screenshots from WordPress 5.2

![2022-05-13_10-11-39](https://user-images.githubusercontent.com/288381/168230724-0d7e5fbd-7aa1-4b6c-9563-c2eb7897f5de.png)

![2022-05-13_10-14-52](https://user-images.githubusercontent.com/288381/168231168-43a33126-5570-4ed3-b1c8-0010660b587c.png)

### WordPress information

```
### wp-core ###

version: 5.2
site_language: en_US
user_language: en_US
permalink: /%postname%/
https_status: false
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html
wordpress_size: 37.38 MB (39199573 bytes)
uploads_path: /var/www/html/wp-content/uploads
uploads_size: 0.00 B (0 bytes)
themes_path: /var/www/html/wp-content/themes
themes_size: 8.57 MB (8982790 bytes)
plugins_path: /var/www/html/wp-content/plugins
plugins_size: 209.24 MB (219402006 bytes)
database_size: 2.11 MB (2211840 bytes)
total_size: 257.30 MB (269796209 bytes)

### wp-active-theme ###

name: Twenty Nineteen
version: 1.4 (latest version: 2.2)
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, title-tag, post-thumbnails, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, editor-color-palette, responsive-embeds, widgets
theme_path: /var/www/html/wp-content/themes/twentynineteen

### wp-themes (8) ###

Twenty Eleven: version: 3.3, author: the WordPress team (latest version: 4.0)
Twenty Fifteen: version: 2.5, author: the WordPress team (latest version: 3.1)
Twenty Fourteen: version: 2.7, author: the WordPress team (latest version: 3.3)
Twenty Seventeen: version: 2.2, author: the WordPress team (latest version: 2.9)
Twenty Sixteen: version: 2.0, author: the WordPress team (latest version: 2.6)
Twenty Ten: version: 2.9, author: the WordPress team (latest version: 3.6)
Twenty Thirteen: version: 2.9, author: the WordPress team (latest version: 3.5)
Twenty Twelve: version: 3.0, author: the WordPress team (latest version: 3.6)

### wp-plugins-active (1) ###

Block for Apple Maps: version: 1.0.2, author: 10up

### wp-plugins-inactive (1) ###

Hello Dolly: version: 1.7.2, author: Matt Mullenweg

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1691
imagemagick_version: ImageMagick 6.9.11-60 Q16 aarch64 2021-01-25 https://imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.53.3

### wp-server ###

server_architecture: Linux 5.10.47-linuxkit aarch64
httpd_software: Apache/2.4.53 (Debian)
php_version: 7.4.29 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: -1
upload_max_size: 2M
php_post_max_size: 8M
curl_version: 7.74.0 OpenSSL/1.1.1n
suhosin: false
imagick_availability: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.5.5-10.7.3-MariaDB-1:10.7.3+maria~focal
client_version: mysqlnd 7.4.29

### wp-constants ###

WP_HOME: http://localhost:8889/
WP_SITEURL: http://localhost:8889/
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cadic** [comment]
Does it worth to fix issues or just bump "Requires at least:" to the newer version (5.5)?

**Comment by fabiankaegy** [comment]
As far as I'm aware the experimental components we use in the block itself since https://github.com/10up/maps-block-apple/pull/115 make it so that the block requires 5.8 I believe to work. So I think we will need to update the required minimum version

**Comment by cadic** [comment]
@fabiankaegy That's right, the block is only become available in 5.8, so I believe we can bump minimum support to that release.

**Comment by jeffpaul** [comment]
@cadic works for me, bump the WP minimum and make this easier all around!

**Comment by jeffpaul** [comment]
@cadic to confirm, bumping WP minimum to 5.8 (in both readmes) should resolve this issue and unblock #126?

**Comment by jeffpaul** [comment]
@cadic want to update #126 to include the WP min bump to 5.8 and mark that PR as closing this issue as well?

**Comment by cadic** [comment]
@jeffpaul minimum WP bumped in #126, so this issue should be auto-closed once it is merged
