### ISSUE TITLE
Update PHPCS action to avoid deprecation warning.

### ISSUE THREAD

**Issue by peterwilsoncc** [10up/maps-block-apple#143]
### Describe the bug

The PHPCS workflow is currently failing due to a deprecation warning. This in turn blocks the merge of pull requests.

### Steps to Reproduce

[See checks on another PR.](https://github.com/10up/maps-block-apple/actions/runs/3482638246/jobs/5825188396)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Alternatively if we shipped the minor release on the WPCS action that would resolve this as well, yeah?

**Comment by peterwilsoncc** [comment]
Yes, that would fix it too.

**Comment by peterwilsoncc** [comment]
Resolved upstream.
