### ISSUE TITLE
After download and install latest copy of plugin file getting fatal error

### ISSUE THREAD

**Issue by QAharshalkadu** [10up/maps-block-apple#177]
### Describe the bug

After downloading and installing the latest copy of the plugin file I got a fatal error.

Tested on WordPress version 6.3

### Steps to Reproduce

1 Download the plugin zip file latest version from Github: https://github.com/10up/maps-block-apple
2 Try to upload and install this plugin zip file into site
3 Observe > Getting fatal error

### Screenshots, screen recording, code snippet

![image](https://github.com/10up/maps-block-apple/assets/137804688/7b999209-82b2-4d84-b90d-6cc2cecb8e8a)

### Environment information

Windows 11, Chrome browser Version 116.0.5845.111 (Official Build) (64-bit)
WordPress version 6.3

### WordPress information

WordPress version 6.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
@QAharshalkadu based on the error it shows it looks like you may have downloaded the development version of the code which needs to be built before it works.

Can you elaborate where and how exactly you downloaded it?

**Comment by QAharshalkadu** [comment]
@fabiankaegy I downloaded this zip file from GitHub URL: https://github.com/10up/maps-block-apple
Option "Code" > Download zip
![image](https://github.com/10up/maps-block-apple/assets/137804688/12be6a7f-b427-4fe4-b81d-0e2a0924d9ed)

**Comment by fabiankaegy** [comment]
@QAharshalkadu okay yes. That is the source code only. Which is what causes the issue for you

**Comment by QAharshalkadu** [comment]
@fabiankaegy I got the correct zip file now and tried to upload and install it. It's working for me now.
Status: Not an issue

![image](https://github.com/10up/maps-block-apple/assets/137804688/2cdbd7f2-d9d0-4ab5-b03b-7e4efffe077b)

Thank you!
