### ISSUE TITLE
Apple Maps block gives error in WP 6.4-beta2 if MapKit Credentials is not configured.

### ISSUE THREAD

**Issue by iamdharmesh** [10up/maps-block-apple#182]
### Describe the bug

While debugging on E2E test failure on the WP trunk (WP 6.4-beta), I found that the Apple Maps block gives `This block has encountered an error and cannot be previewed.` error in WP 6.4-beta2 if MapKit Credentials is not configured.

Based on initial findings it seems, the issue is caused due to recent accessibility improvements in placeholder instructions (https://github.com/WordPress/gutenberg/pull/45801), The placeholder component expects raw string in instructions but the plugin passes the `<IsAdmin>` component, which causes the issue with [call to speak function](https://github.com/WordPress/gutenberg/blob/4b10f653ba12baebd374dacdb2df2d93c017a422/packages/components/src/placeholder/index.tsx#L84) and block encounter an error.

### Steps to Reproduce

1. Install and activate the plugin on WP 6.4-beta-2
2. Keep Mapkit js credentials blank
3. Go to create post/page and add "Apple Maps" block
4. Notice error `This block has encountered an error and cannot be previewed.` error

### Screenshots, screen recording, code snippet

![image](https://github.com/10up/maps-block-apple/assets/10613171/9c6884d8-47d1-4b94-9146-ca2a06cd2f77)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
Great find on what's causing the issue. Let's see if we can help fix this in core before the 6.4 release.

**Comment by iamdharmesh** [comment]
@fabiankaegy Based on comment [here](https://github.com/WordPress/gutenberg/pull/45801#issuecomment-1743821275) it needs to be fixed here in `maps-block-apple` as well. right? What do you think?

> The `instructions` prop is meant to accept raw strings. Instead, in your code you're passing a React element. It may have accidentally worked in previous versions of the Gutenberg plugin/WordPress, but the prop was always meant to be a `string`.

**Comment by fabiankaegy** [comment]
Ahh yeah, I had missed that in the comments. That is annoying. Thanks for pointing it out. 

In that case yeah we will need to precompute all that logic and then only pass in the processed string.

**Comment by iamdharmesh** [comment]
@fabiankaegy I have raised a fix PR for this with a slightly different approach by dropping the usage of the `instructions` prop of Placeholder. Instructions contain a link to Mapkit docs and  I didn't find any way to add link instructions while keeping instructions as a raw string (Maybe there is a way but I am not aware of it). Please let me know if you think we could have a better approach here.

Thanks
