### ISSUE TITLE
No translations are loaded for the scripts

### ISSUE THREAD

**Issue by jeffpaul** [10up/maps-block-apple#213]
### Is your enhancement related to a problem? Please describe.

In running the [Block Plugin Checker](https://wordpress.org/plugins/developers/block-plugin-validator/) on this project, it has a recommendation on "No translations are loaded for the scripts":

> Block plugins should use `wp_set_script_translations` to load translations for each script file. [Learn more about internationalization.](https://developer.wordpress.org/block-editor/developers/internationalization/)

It would be helpful to assess if there are changes needed within the Apple Maps block plugin on this matter and if so work on updating so that translations load as and where expected.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thrijith** [comment]
Hi @jeffpaul it looks like it is no longer an issue, tested today and it is not showing the error you mentioned above.

https://cleanshot.thrijith.com/g4Ybg7DGwHswFLs1cVJ8
