### ISSUE TITLE
Validation errors when admin URL is different from site URL

### ISSUE THREAD

**Issue by ryanwelcher** [10up/maps-block-apple#34]
**Describe the bug**
In testing a zip, I discovered if WordPress installed in a subdirectory, the request made to authenticate fails.

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by dinhtungdu** [comment]
I can't reproduce this issue. Look like it was fixed by 92f03d08e5ec36f179b4c7fa94ac8112dde3878a
