### ISSUE TITLE
block.json syntax error

### ISSUE THREAD

**Issue by jeffpaul** [10up/maps-block-apple#75]
**Describe the bug**
I ran the block thru https://wordpress.org/plugins/developers/block-plugin-validator/ now that we've released 1.0.1 in part to help address Block Directory requirements, but am seeing a new error:

> Error attempting to parse json in `block.json`: JSON Parser: Syntax error
> This block.json file is invalid. The Block Directory needs to be able to read this file.

Checking a JSON parser it looks like maybe the `icon` element’s SVG reference in [block.json](https://github.com/10up/maps-block-apple/blob/develop/block.json) is a potential cause.  According to [Gutenberg’s Block Type Metadata doc](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/block-metadata.md#icon), it sounds like an SVG is viable and maybe we just need to wrap that as a string?  I tested adding the block via the block directory in a new wp 5.5 install and everything works as expected, including the display of the SVG icon.

**Steps to Reproduce**

1. Go to https://wordpress.org/plugins/developers/block-plugin-validator/
2. Add https://plugins.svn.wordpress.org/maps-block-apple/ into the text field
3. Click "Check Plugin!" button

**Expected behavior**
All Block Directory checks pass successfully.

**Screenshots**

**Environment information**
n/a, this isn't an error on a WP instance but with the Block Checker/Validator

**Additional context**

Prior `block.json` PR --> https://github.com/10up/maps-block-apple/pull/63

**Comment by ryanwelcher** [comment]
@jeffpaul the issue is most likely with both the [icon](https://github.com/10up/maps-block-apple/blob/develop/block.json#L5) and [keywords](https://github.com/10up/maps-block-apple/blob/develop/block.json#L7) fields in `block.json`.

Change the keywords line to `"keywords": [ "apple", "map", "apple map" ]` and remove the SVG code. Does the block directory use that icon?
