### ISSUE TITLE
Internationalize plugin

### ISSUE THREAD

**Issue by helen** [10up/maps-block-apple#8]
Needs a text-domain plugin header and a review of all localization function calls to ensure the domain is used and strings are constructed properly.

**Comment by jeffpaul** [comment]
Per the [Block Plugin Checker](https://wordpress.org/plugins/developers/block-plugin-validator/):
> **No translations are loaded for the scripts.**
> Block plugins should use `wp_set_script_translations` to load translations for each script file. [Learn more about internationalization.](https://developer.wordpress.org/block-editor/developers/internationalization/)
